server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8850
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/login/**
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/post/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment/**

